# Generated by Django 2.2.2 on 2019-07-02 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kip_api.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='адрес')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='почта подтверждена')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', kip_api.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('detail_program', models.URLField(blank=True, verbose_name='Ссылка на программу курса')),
                ('short_schedule', models.CharField(blank=True, max_length=255, verbose_name='Недельное расписание')),
                ('closed', models.BooleanField(default=False, verbose_name='Обучение закончено')),
            ],
            options={
                'verbose_name': 'Группа курса',
                'verbose_name_plural': 'Группы курсов',
                'db_table': 'courses_groups',
            },
        ),
        migrations.CreateModel(
            name='CoursesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новая категория', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории курсов',
                'db_table': 'courses_categories',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('number', models.IntegerField(verbose_name='№ урока в курсе')),
                ('start', models.DateTimeField(blank=True, verbose_name='Начало')),
                ('duration', models.IntegerField(default=2, verbose_name='Длительность')),
                ('meeting_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на вебинар')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kip_api.CourseGroup', verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lessons',
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(blank=True, verbose_name='О себе')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Студент'), (2, 'Преподаватель')], default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='kip_api.CourseGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участие в группах',
                'verbose_name_plural': 'Участие в группах',
                'db_table': 'participations',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый курс', max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kip_api.CoursesCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Наименование курса',
                'verbose_name_plural': 'Наименования курсов',
                'db_table': 'courses',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kip_api.Courses', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='participants',
            field=models.ManyToManyField(related_name='courses_groups', through='kip_api.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', through='kip_api.Participation', to='kip_api.CourseGroup', verbose_name='Учебные группы'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='UserLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.IntegerField(choices=[(5, 'Не задано'), (1, 'Не сдано'), (1, 'Отправлено на доработку'), (2, 'Принято'), (3, 'Отправлено на проверку'), (4, 'Принято на проверку')], default=1, verbose_name='Домашнее задание')),
                ('paid', models.BooleanField(default=False, verbose_name='оплачено')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_status', to='kip_api.Lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_status', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Занятия пользователей',
                'db_table': 'lessons_status',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursegroup',
            unique_together={('course', 'name')},
        ),
    ]
