# Generated by Django 2.2.5 on 2019-10-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kip_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Студент'), (2, 'Преподаватель')], default=1),
        ),
    ]
