# Generated by Django 2.2.5 on 2019-09-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kip_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='logo',
            field=models.TextField(blank=True, verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='courses',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
