# Generated by Django 2.2.3 on 2019-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kip_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessons',
            name='homework',
            field=models.IntegerField(choices=[(5, 'Не задано'), (0, 'Не сдано'), (1, 'Отправлено на доработку'), (2, 'Принято'), (3, 'Отправлено на проверку'), (4, 'Принято на проверку')], default=0, verbose_name='Домашнее задание'),
        ),
    ]
