# Generated by Django 2.2.5 on 2019-09-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kip_api', '0005_auto_20190925_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='images/avatars/'),
        ),
    ]
