# Generated by Django 2.2.5 on 2019-09-26 06:28

from django.db import migrations, models
import kip_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('kip_api', '0007_auto_20190926_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpeg', upload_to=kip_api.utils.image_file_name),
        ),
    ]
