# Generated by Django 2.2.5 on 2019-09-26 08:08

from django.db import migrations, models
import kip_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('kip_api', '0008_auto_20190926_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/home/sergey/dev/projects/kip/images/default_avatar.jpeg', upload_to=kip_api.utils.image_file_name),
        ),
    ]
