# Generated by Django 2.2.5 on 2019-09-26 08:54

from django.db import migrations, models
import kip_api.utils
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('kip_api', '0009_auto_20190926_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/images/default_avatar.jpeg', upload_to=kip_api.utils.image_file_name, validators=[upload_validator.FileTypeValidator(allowed_extensions=['.jpg', '.jpeg', '.png'], allowed_types=['image/jpeg', 'image/png'])]),
        ),
    ]
