# Generated by Django 2.2.5 on 2019-09-26 09:04

from django.db import migrations, models
import kip_api.utils
import kip_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('kip_api', '0010_auto_20190926_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=kip_api.utils.image_file_name, validators=[kip_api.validators.validate_image]),
        ),
    ]
