image: docker:latest

variables:
  VERSION: '1.0'

services:
  - docker:dind

before_script:
  - docker info

stages:
  - build

build:
  stage: build
  script:
    - docker build -t drcoyote/kip_backend:$VERSION .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker tag drcoyote/kip_backend:$VERSION
    - docker push $CI_REGISTRY_USER/kip_backend:$VERSION
