image: docker:latest

variables:
  VERSION: '1.0'

services:
  - docker:dind

before_script:
  - docker info

stages:
  - build

build:
  stage: build
  script:
    - docker build -t registry.sk-developer.ru/kip_backend:$VERSION -t registry.sk-developer.ru/kip_backend:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.sk-developer.ru
    - docker push registry.sk-developer.ru/kip_backend:$VERSION
    - docker push registry.sk-developer.ru/kip_backend:latest
    - docker logout
