dist: xenial
language: python
sudo: required

services:
  - docker
python:
  - '3.7'
install:
  - sudo apt-get install python-tk
  - pip install -r requirements.txt
script:
  - docker build -t drcoyote/kip_api:backend_latest .
notifications:
  slack:
    secure: lkXxen9fPoNpoVGhR3/ciUaNsEo0euuQO6rTMNZWB6vm1+cQjfZx+lg2RpGdvDbjefblTGmlqXzhj5wOMR75HC/B1UkzWewz+ICjD0wCQ/3lxVgAphmy8XEFI1FHV/tP4ZmhoJnTQnOhwdovVcddQj82yzjq3sKmQVxF9AJXulYabzLsKTkm5ODYhVcWjXmjUs87eBt3sIbShYuJifzwb+3DRGx7md7SwlCWVF9EQr+khfnWlxHIuLGscKc7f6I8VjLOBIyA9DSLdnjK9ObGy6WHx3e4oqpH0UKcG7OiO1+z8VxJ5OA9c9bGc9CjwBZhLA1rS8H6eBR/U2VIKakZoaMZs/Jmtby5vcbUe90fnnBTSLNb4mhK4xD3CFHSDj3904rdAor9PYrAnrJGaN74E25WdES+qTbL2wJ2RaWI9n3R08DnSzW4EXJ6eN5JbSxkE4sD/5MjtS44rNK10pLCZE0ZtPBSPnabQvjPrG5BHotnE2//Syleh1yu67SxS4JfeSHI4pJwYEh0xTDP/ScnvkNm7h7NPwUewWcDYnATLpvL/Ifa3cqXf120xsxvFDnKA+sE5SObGHRg0lIlOTElKGtUpzJXscKahMt35SAW3k9pLdtNsMjKwW2IUtM5lN+fu1YLsrGG7X+SPejQhn7SC+XyzX57SMz463lKcYTB4ic=
