#
# Запуск сервисов проекта KIP!
#

version: '3'

services:

  database:
    image: mariadb:10.3
    restart: always
    container_name: kip_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: kip
    volumes:
      - ./init.sql:/data/application/init.sql
      - ~/kip/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql

  kip:
    build: .
    image: registry.sk-developer.ru/kip_backend:latest kip_ap
    container_name: kip_api
    restart: always
    ports:
      - 8000:8000
    links:
      - database:db
      - fluentd
    depends_on:
      - database
    volumes:
      - ~/kip/media/images:/app/images
      - ~/kip/media/images/avatars:/app/images/avatars
    environment:
      RMQ_HOST: 127.0.0.1
      RMQ_PORT: 5672
      RMQ_USERNAME: guest
      RMQ_PASSWORD: guest
      DB_USER: kip
      DB_PASSWORD: VFERGUSON11284kip
      DB_HOST: database
      DB_PORT: 3306
      DJANGO_SETTINGS_MODULE: kip.settings
      ACCESS_TOKEN_LIMIT: 365
      REFRESH_TOKEN_LIMIT: 1
      PORT: 8000
      DEBUG: 0
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: api

  #
  # Так как сервис API запускается под gunicorn, а он статику отдавать не умеет,
  # подключаем nginx, так как мы хотим видеть админку красивой со всеми CSS и прочим
  #
  nginx:
    image: nginx:1.17
    container_name: kip_nginx
    links:
      - kip
    ports:
       - 80:80
    volumes:
       - ./nginx:/etc/nginx/conf.d
       - ~/static:/static

#  fluentd:
#    build: ./fluentd
#    container_name: kip_fluentd
#    links:
#      - "elasticsearch"
#    ports:
#      - "24224:24224"
#      - "24224:24224/udp"

#  elasticsearch:
#    image: elasticsearch:6.7.0
#    container_name: kip_es
#    expose:
#      - 9200
#    ports:
#      - "9200:9200"
#    volumes:
#      - ~/kip_es/data:/var/lib/elasticsearch
#
#  kibana:
#    image: kibana:6.7.0
#    container_name: kip_kibana
#    links:
#      - "elasticsearch"
#    ports:
#      - "5601:5601"
