# docker-compose.yml
version: '2'
services:
    prometheus:
        build: ./prometheus
        volumes:
            - prometheus_data:/prometheus
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
            - '-alertmanager.url=http://alertmanager:9093'
    node-exporter:
        image: prom/node-exporter:v0.18.1
    grafana:
        image: grafana/grafana:6.3.5
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=pass
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - prometheus
    alertmanager:
        build: ./alertmanager
        command:
            - '-config.file=/alertmanager.yml'
    # ssl:
    #     image: opencapacity/lets-nginx:1.3
    #     environment:
    #         - EMAIL=webmaster@
    #         - DOMAIN=test.opencapacity.co
    #         - UPSTREAM=grafana:3000
    #     ports:
    #         - "443:443"
    #     volumes:
    #         - letsencrypt:/etc/letsencrypt
    #         - letsencrypt_backups:/var/lib/letsencrypt
    #         - dhparam_cache:/cache
    #     depends_on:
    #         - grafana
volumes:
    prometheus_data: {}
    grafana_data: {}
    letsencrypt: {}
    letsencrypt_backups: {}
    dhparam_cache: {}
