version: '3.3'

services:
  influxdb:
    image: influxdb:1.7.8
    container_name: influxdb
    ports:
      - 8086:8086
      - 8082:8082
    env_file:
      - 'env.influxdb'
    volumes:
      - ~/kip/influxdb/data:/var/lib/influxdb

  grafana:
      image: grafana/grafana:6.3.5
      container_name: grafana
      env_file:
        - 'env.grafana'
      volumes:
        # При наличии в логах ошибки доступа Grafana к папкам, необходимо выполнить
        # команду: sudo chown 472:472 ~/kip/grafana/ и перезапустить стек
        - ~/kip/grafana:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=secret
      depends_on:
        - influxdb
      ports:
        - 3000:3000

  #
  # Chronograf добавлен в качестве администраивной части InfluxDB,
  # так как сама она ее более не содержит
  #
  chronograf:
      image: chronograf:1.7.14
      environment:
        RESOURCES_PATH: "/usr/share/chronograf/resources"
      volumes:
        - ~/kip/chronograf/data/:/var/lib/chronograf/
      links:
        - influxdb
      ports:
        - 8888:8888
      depends_on:
        - influxdb
